[package]
name = "metrics-fn-example-log"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
metrics-fn = { path = "../metrics-fn", features = [ "record-log" ] }
simple_logger = { version = "5.1" }